"""empty message

Revision ID: 2df500365f9e
Revises: bc981cae2455
Create Date: 2026-03-16 13:34:10.678155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df500365f9e'
down_revision = 'bc981cae2455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_raw', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_html', sa.Text(), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))
        batch_op.drop_column('content_html')
        batch_op.drop_column('content_raw')

    # ### end Alembic commands ###
