"""empty message

Revision ID: d5603b169942
Revises: 79debb2b1e1d
Create Date: 2026-03-21 17:32:04.542294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5603b169942'
down_revision = '79debb2b1e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_images', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
